config/routes.rb
Rails.application.routes.draw do

  root 'static#index'
  get 'static/about'

  resources :meta_analyses
  resources :studies do
    resources :treatments
  end
end

app/models/meta_analysis.rb
class MetaAnalysis < ActiveRecord::Base
  has_many :meta_analysis_treatments
  has_many :treatments, through: :meta_analysis_treatments

  validates :description, presence: true, uniqueness: true
end

app/models/meta_analysis_treatment.rb
class MetaAnalysisTreatment < ActiveRecord::Base
  belongs_to :meta_analysis
  belongs_to :treatment
end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :treatments
  validates :name, :authors, :year, presence: true
  validates :year, numericality: { only_integer: true, greater_than: 0 }

  accepts_nested_attributes_for :treatments, reject_if: :all_blank, allow_destroy: :true
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :study
  has_many :meta_analysis_treatments
  has_many :meta_analyses, through: :meta_analysis_treatments

  validates :description, :effect_size, :standard_error, presence: true
  validates :effect_size, numericality: true
  validates  :standard_error, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meta_analyses_controller.rb
class MetaAnalysesController < ApplicationController
  def index
    flash[:error] = nil
    load_meta_analyses
  end

  def new
    build_meta_analysis
  end

  def edit
    load_meta_analysis
  end

  def create
    build_meta_analysis

    if @meta_analysis.save
      flash[:notice] = "Meta Analysis Successfully Created"
      redirect_to action: 'index'
    else
      flash[:error] = "Please review the problems below"
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    load_meta_analysis
    build_meta_analysis
    if @meta_analysis.save(meta_analysis_params)
      flash[:notice] = "Meta Analysis Successfully Updated"
      redirect_to action: 'index'
    else
      flash[:error] = "Please review the problems below"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    load_meta_analysis
    if @meta_analysis.destroy
      flash[:notice] = "Meta Analysis Successfully Deleted"
      redirect_to action: 'index'
    else
      render 'index', status: :unprocessable_entity
    end
  end

  private

  def load_meta_analyses
    @meta_analyses ||= MetaAnalysis.all
  end

  def load_meta_analysis
    @meta_analysis ||= MetaAnalysis.find(params[:id])
  end

  def build_meta_analysis
    @meta_analysis ||= MetaAnalysis.new
    @meta_analysis.attributes = meta_analysis_params
  end

  def meta_analysis_params
    if params[:meta_analysis]
      params.require(:meta_analysis).
        permit(:description,
              treatment_ids: [])
    else
      {}
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def index
    load_studies
  end

  def show
    load_study
    @treatment = @study.treatments.new
    load_treatments
  end

  def new
    build_study
  end

  def edit
    load_study
  end

  def create
    build_study

    if @study.save
      flash[:notice] = "Study Successfully Created"
      flash[:error] = nil
      redirect_to action: 'index'
    else
      flash[:error] = "Please review the problems below"
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    load_study
    build_study
    if @study.save
      flash[:notice] = "Study Successfully Updated"
      flash[:error] = nil
      redirect_to action: 'index'
    else
      flash[:error] = "Please review the problems below"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    load_study
    if @study.destroy
      flash[:notice] = "Study Successfully Deleted"
      flash[:error] = nil
      redirect_to action: 'index'
    else
      render 'index', status: :unprocessable_entity
    end
  end

  private

  def load_treatments
    @treatments ||= Treatment.where(study: @study)
  end

  def load_studies
    @studies ||= Study.all
  end

  def load_study
    @study ||= Study.find(params[:id])
  end

  def build_study
    @study ||= Study.new
    @study.attributes = deal_with_nested_params(study_params)
  end

  def deal_with_nested_params(params)
    if params['treatments_attributes']
      sub_params_with_numeric_keys = params['treatments_attributes']
      params['treatments_attributes'] = sub_params_with_numeric_keys.values
    end
    params
  end

  def study_params
    if params[:study]
      params.require(:study).
        permit(:name,
               :authors,
               :year,
               treatments_attributes: [:id,
                                       :description,
                                       :effect_size,
                                       :standard_error,
                                       :_destroy])
    else
      {}
    end
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

  def edit
    load_study
    load_treatment
  end

  def create
    build_treatment

    if @treatment.save
      flash[:notice] = "Treatment Successfully Created"
      flash[:error] = nil
      redirect_to study_path(@study)
    else
      flash[:error] = "Unable to Save Treatment. Please ensure fields are filled properly"
      redirect_to study_path(@study)
    end
  end

  def update
    load_treatment
    load_study
    build_treatment
    if @treatment.save
      flash[:notice] = "Treatment Successfully Updated"
      flash[:error] = nil
      redirect_to study_path(@study)
    else
      flash[:error] = "Please review the problems below"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    load_treatment
    if @treatment.destroy
      flash[:notice] = "Treatment Successfully Deleted"
      flash[:error] = nil
      redirect_to study_path(@study)
    else
      flash[:error] = "Something Went Wrong"
      redirect_to study_path(@study)
    end
  end

  private

  def load_study
    @study ||= Study.find(params[:study_id])
  end

  def load_treatment
    @treatment ||= Treatment.find(params[:id])
  end

  def build_treatment
    @treatment ||= load_study.treatments.new
    @treatment.attributes = treatment_params
  end

  def treatment_params
    if params[:treatment]
      params.require(:treatment).
        permit( :description,
               :effect_size,
               :standard_error)
    else
      {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(text, path)
    options = current_page?(path) ? { class: "active"}: {}
    content_tag(:li, options) do
      link_to text, path
    end
  end

  def css_class_for_flash_type(flash_type)
    css_classes_for_flash_type = {
      notice: 'alert-success',
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      info: 'alert-info'
    }
    css_classes_for_flash_type[flash_type.to_sym]
  end
end

app/views/application/_flashes.html.erb
<% %i(notice success error alert info).each do |status| %>
  <% if flash[status] %>
    <div class="row">
      <div class="alert alert-block <%= css_class_for_flash_type(status) %>">
        <button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
        <%= flash[status] %>
      </div>
    </div>
  <% end %>
<% end %>
<div id="flash"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetaAnalyzer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Meta Analyzer</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <%= nav_bar do %>
            <%= nav_link "Home", root_path %>
            <%= nav_link "Meta Analyses", meta_analyses_path %>
            <%= nav_link "Studies", studies_path %>
            <%= nav_link "About", static_about_path  %>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/meta_analyses/_form.html.erb
<%= simple_form_for @meta_analysis, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :description, wrapper: :horizontal_form %>
  <%= f.association :treatments,
    as: :check_boxes,
    wrapper: :horizontal_scrollable,
    label_method: ->(treatment) { "#{treatment.study.name} - #{treatment.description.truncate(100)}" } %>
  <div class="form-actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
      <%= link_to "Cancel", meta_analyses_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/meta_analyses/edit.html.erb
<h2>Edit Meta Analysis</h2>
<%= render 'flashes' %>
<%= render 'form' %>

app/views/meta_analyses/index.html.erb
<h2>Your Meta Analyses</h2>
<%= render 'flashes' %>
<table class="table table-striped data-table">
  <thead>
    <th>ID</th>
    <th>Description</th>
    <th></th>
  </thead>
  <tbody>
    <% @meta_analyses.each do |analysis| %>
      <tr>
        <td><%= analysis.id %></td>
        <td><%= analysis.description %></td>
        <td>
          <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-cog"></i>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right">
              <li><%= link_to 'Edit', edit_meta_analysis_path(analysis) %></li>
              <li><%= link_to 'Delete', meta_analysis_path(analysis), method: :delete, title: 'Delete', data: { confirm: "Are you sure?" } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New Meta Analysis", new_meta_analysis_path, class: 'btn btn-primary' %>

app/views/meta_analyses/new.html.erb
<h2>New Meta Analysis</h2>
<%= render 'flashes' %>
<%= render 'form' %>

app/views/studies/_treatment_fields.html.erb
<div class="nested-fields">
  <%= f.input :description, wrapper: :horizontal_form %>
  <%= f.input :effect_size,
    as: :decimal,
    input_html: { min: '0', step: 'any' },
    wrapper: :horizontal_form %>
  <%= f.input :standard_error, as: :decimal, wrapper: :horizontal_form %>
  <%= link_to_remove_association f do %>
    <i class="fa fa-minus-square-o"></i> Remove Treatment
  <% end %>
</div>

app/views/studies/edit.html.erb
<h2>Edit Study</h2>
<%= render 'flashes' %>
<%= simple_form_for @study, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :name, wrapper: :horizontal_form %>
  <%= f.input :authors, wrapper: :horizontal_form %>
  <%= f.input :year, as: :integer, wrapper: :horizontal_form %>
  <div class="form-actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
      <%= link_to "Cancel", studies_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/studies/index.html.erb
<h2>Your Studies</h2>
<%= render 'flashes' %>
<table class="table table-striped data-table">
  <thead>
    <th>ID</th>
    <th>Name</th>
    <th>Authors</th>
    <th>Year</th>
    <th></th>
  </thead>
  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.id %></td>
        <td><%= link_to study.name, study_path(study) %></td>
        <td><%= study.authors %></td>
        <td><%= study.year %></td>
        <td>
          <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-cog"></i>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right">
              <li><%= link_to 'Edit', edit_study_path(study) %></li>
              <li><%= link_to 'Delete', study_path(study), method: :delete, title: 'Delete', data: { confirm: "Are you sure?" } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New Study", new_study_path, class: 'btn btn-primary' %>

app/views/studies/new.html.erb
<h2>New Study</h2>
<%= render 'flashes' %>
<%= simple_form_for @study, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :name, wrapper: :horizontal_form %>
  <%= f.input :authors, wrapper: :horizontal_form %>
  <%= f.input :year, as: :integer, wrapper: :horizontal_form %>
  <h3>Treatments</h3>
  <%= f.simple_fields_for :treatments do |treatment| %>
    <%= render partial: 'treatment_fields', locals: { f: treatment } %>
  <% end %>
  <div class="links">
    <%= link_to_add_association f, :treatments do %>
      <i class="fa fa-plus-square-o"></i> Add Treatment
    <% end %>
  </div>
  <div class="form-actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
      <%= link_to "Cancel", studies_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/studies/show.html.erb
<p class="h3 pull-right">
  <%= link_to edit_study_path(@study), class: "btn btn-default" do %>
    <i class="fa fa-pencil"></i>
  <% end %>
  <%= link_to study_path(@study), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" do %>
    <i class="fa fa-trash"></i>
  <% end %>
</p>
<h2><%= "#{@study.name}" %></h2>
<div class="panel">
  <dl class="dl-horizontal">
    <dt>Authors</dt>
    <dd><%= @study.authors %></dd>
    <dt>Year</dt>
    <dd><%= @study.year %></dd>
  </dl>
</div>
<h3>New Treatment</h3>
<%= render 'flashes' %>
<%= simple_form_for [@study, @treatment],
  html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :description, wrapper: :horizontal_form %>
  <%= f.input :effect_size,
    as: :decimal,
    input_html: { min: '0', step: 'any' },
    wrapper: :horizontal_form %>
  <%= f.input :standard_error, as: :decimal, wrapper: :horizontal_form %>
  <div class="form-actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
      <%= link_to "Cancel", study_path(@study), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
<h3>Treatments</h3>
<table class="table table-striped data-table">
  <thead>
    <th>ID</th>
    <th>Description</th>
    <th>Effect Size</th>
    <th>Standard Error</th>
    <th></th>
  </thead>
  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= treatment.id %></td>
        <td><%= treatment.description %></td>
        <td><%= treatment.effect_size %></td>
        <td><%= treatment.standard_error %></td>
        <td>
          <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-cog"></i>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right">
              <li><%= link_to 'Edit', edit_study_treatment_path(@study, treatment) %></li>
              <li><%= link_to 'Delete', study_treatment_path(@study, treatment), method: :delete, title: 'Delete', data: { confirm: "Are you sure?" } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/treatments/_form.html.erb
<%= simple_form_for [@study, @treatment], html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :description, wrapper: :horizontal_form %>
  <%= f.input :effect_size,
    as: :decimal,
    input_html: { min: '0', step: 'any' },
    wrapper: :horizontal_form %>
  <%= f.input :standard_error, as: :decimal, wrapper: :horizontal_form %>
  <div class="form-actions form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
      <%= link_to "Cancel", studies_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h2>Edit Treatment</h2>
<%= render 'flashes' %>
<%= render 'form' %>